title: Hello, world! I'm David Freeman
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://techbyte.me" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: KD # add your name
author-img: profile.png # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
twitter: gpaidapps # add your Twitter handle
facebook: u4i.me # add your Facebook handle
github: github # add your Github handle
linkedin: # add your Linkedin handle
email: kd@datamail.in # add your Email address

# Disqus
discus-identifier: nowuseme # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
